# Generated by Django 3.2.20 on 2023-10-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='expiration',
            field=models.DateTimeField(default='1970-01-01T00:00:00Z'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
